steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'Dockerfile.cuda-headers', '--build-arg', 'BASE_IMAGE=${_BASE_IMAGE}', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
timeout: 1200s
